// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjshjcfwqhcpcbqvibpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqc2hqY2Z3cWhjcGNicXZpYnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjIyMjQsImV4cCI6MjA2MTYzODIyNH0.udNC81Y7Mlaus7Lx9IyA1r9yXqU4nfZHB5MJ-9ceAsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);